#!/bin/sh
#
# Starts retroarch
#

NAME=retroarch
BIN=/usr/bin/retroarch
PIDFILE=/var/run/retroarch.pid
ARGS="-v"
DISPLAY=:0.0

start() {
	printf "Starting ${NAME}: "
	start-stop-daemon -S -q -b -m -p ${PIDFILE} --exec ${BIN} -- ${ARGS}
	[ $? = 0 ] && sleep 3 && echo "OK" || echo "FAIL"
}

stop() {
	printf "Stopping ${NAME}: "
	start-stop-daemon -K -q -p ${PIDFILE}
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}

restart() {
	stop
	sleep 2
	start
}

case "$1" in
	start)
		start
	;;
	stop)
		stop
	;;
	restart|reload)
		restart
	;;
	*)
		echo "Usage: $0 {start|stop|restart}"
	exit 1
esac
